services:
  frontend:
   user: "33:33"
   build:
     context: ./frontend
     network: host
   ports:
     - "3000:3000"
   depends_on:
     - backend
   volumes:
     - ./frontend/uploads:/app/uploads
   environment:
     - NEXT_CACHE_DIR=/tmp/next-cache

  backend:
   build:
     context: ./backend
     network: host
   ports:
     - "8000:8000"
   env_file:
     - ./backend/.env
   environment:
     - CELERY_BROKER_URL=redis://redis:6379/0
     - CELERY_RESULT_BACKEND=redis://redis:6379/0
   volumes:
     - ./backend/data:/app/data
     - ./frontend/uploads:/app/uploads
   depends_on:
     - redis
     - chromadb

  celery:
    build:
      context: ./backend
      network: host
    command: celery -A app.task_queue.celery_app worker --loglevel=info
    env_file:
      - ./backend/.env
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    volumes:
      - ./backend/data:/app/data
      - ./frontend/uploads:/app/uploads
    depends_on:
     - backend
     - redis
     - chromadb

  redis:
    image: redis:7.2-alpine
    restart: always
    ports:
      - "6379:6379"

  chromadb:
    image: chromadb/chroma:latest
    restart: always
    command: chroma run --host 0.0.0.0 --port 8001 --path /chroma/chroma
    ports:
      - "8001:8001"   # Host:Container
    volumes:
      - ./backend/data/vector_db:/chroma/chroma
    environment:
      - IS_PERSISTENT=TRUE